import argparse
import logging
import os
import random
import time
from datetime import timedelta

from dynamic_des import ParquetStorageEgress, SimulationContext

def create_ecommerce_router(base_path: str):
    """
    Routes the events generated by the simulation into distinct Parquet files
    (e.g., customers.parquet, orders.parquet).
    """
    def router(data: dict) -> str | None:
        # Ignore internal system events and telemetry
        if data.get("path_id") == "system.simulation.lag_seconds":
            return None
        
        stream_type = data.get("stream_type")
        if stream_type == "telemetry":
            return None

        # Flatten event and route based on our custom "type" key
        if stream_type == "event" and "value" in data and isinstance(data["value"], dict):
            nested_value = data.pop("value")
            
            # Strip dynamic-des internal metadata columns
            for k in ["stream_type", "sim_ts", "timestamp", "key", "path_id", "source"]:
                data.pop(k, None)
                
            event_type = nested_value.pop("type", "unknown")
            data.update(nested_value)
            
            if event_type in ["customer", "product", "order", "order_item", "return", "payment"]:
                return f"{base_path}/{event_type}s/{event_type}s.parquet"
            
        return None
    return router


def run_simulation(args):
    # Setup logging & determinism
    logging.basicConfig(level=logging.INFO)
    logger = logging.getLogger(__name__)
    random.seed(args.random_seed)

    logger.info("="*40)
    logger.info("⚙️  DATA GENERATOR CONFIGURATION")
    logger.info(f"Target Path:    {args.dest_path}")
    logger.info(f"Storage Type:   {'S3' if args.use_s3 else 'Local'}")
    logger.info(f"Sim Days:       {args.days}")
    logger.info(f"Batch Size:     {args.batch_size} (Dictates Parquet file size)")
    logger.info("="*40)

    filesystem = None
    if args.use_s3:
        from pyarrow import fs
        filesystem = fs.S3FileSystem(
            access_key=os.getenv("S3_ACCESS_KEY", "user"),
            secret_key=os.getenv("S3_SECRET_KEY", "password"),
            endpoint_override=os.getenv("S3_ENDPOINT", "http://localhost:8333"),
            scheme="http",
        )
        bucket = args.dest_path.replace("s3://", "").split("/")[0]
        try:
            filesystem.create_dir(bucket)
        except Exception:
            pass
    else:
        os.makedirs(args.dest_path, exist_ok=True)

    router = create_ecommerce_router(args.dest_path)

    app = (
        SimulationContext(sim_id="ECommerce", factor=0.0, random_seed=args.random_seed)
        .add_egress(ParquetStorageEgress(path_router=router, filesystem=filesystem))
        .with_batching(batch_size=args.batch_size, flush_interval=86400)
        .add_arrival("customer_signup", dist="exponential", rate=100.0 / 86400)
        .add_arrival("order_placement", dist="exponential", rate=1000.0 / 86400)
        .add_resource("data_generator", current_cap=1000, max_cap=1000)
        .add_service("event_emitter", dist="deterministic", mean=0.0)
    )

    customer_pool = []
    product_pool = []

    @app.task(service_id="event_emitter", resource_id="data_generator")
    def emit_event(event_dict, context):
        return event_dict

    @app.arrival_loop("customer_signup")
    def generate_customers(context):
        if not product_pool:
            categories = ["Electronics", "Clothing", "Home", "Sports", "Toys"]
            for i in range(1, 21):
                product = {
                    "type": "product",
                    "product_id": i,
                    "product_name": f"Product_{i}",
                    "category": random.choice(categories),
                    "price": round(random.uniform(10.0, 500.0), 2),
                    "stock_quantity": random.randint(0, 1000),
                    "created_at": context.env.start_datetime + timedelta(seconds=context.env.now)
                }
                product_pool.append(product)
                context.spawn(emit_event(product, context))
                
        customer_id = 1
        while True:
            yield context.wait_for_arrival("customer_signup")
            customer = {
                "type": "customer",
                "customer_id": customer_id,
                "first_name": f"FirstName_{customer_id}",
                "last_name": f"LastName_{customer_id}",
                "loyalty_tier": random.choice(["Bronze", "Silver", "Gold", "Platinum"]),
                "created_at": context.env.start_datetime + timedelta(seconds=context.env.now)
            }
            customer_pool.append(customer)
            context.spawn(emit_event(customer, context))
            customer_id += 1

    @app.arrival_loop("order_placement")
    def generate_orders(context):
        order_id = 1
        order_item_id = 1
        return_id = 1
        
        while True:
            yield context.wait_for_arrival("order_placement")
            
            if not customer_pool or not product_pool:
                continue
                
            customer = random.choice(customer_pool)
            num_items = random.randint(1, 5)
            total_amount = 0
            order_date = (context.env.start_datetime + timedelta(seconds=context.env.now))
            
            order_status = random.choice(["pending", "shipped", "delivered", "cancelled"])
            
            for _ in range(num_items):
                product = random.choice(product_pool)
                quantity = random.randint(1, 3)
                total_price = product["price"] * quantity
                total_amount += total_price
                
                is_returned = False
                if order_status == "delivered":
                    is_returned = random.random() < 0.1
                
                order_item = {
                    "type": "order_item",
                    "order_item_id": order_item_id,
                    "order_id": order_id,
                    "product_id": product["product_id"],
                    "quantity": quantity,
                    "unit_price": product["price"],
                    "total_price": total_price,
                    "is_returned": is_returned,
                    "created_at": order_date
                }
                context.spawn(emit_event(order_item, context))
                
                if is_returned:
                    ret = {
                        "type": "return",
                        "return_id": return_id,
                        "order_id": order_id,
                        "customer_id": customer["customer_id"],
                        "product_id": product["product_id"],
                        "refund_amount": total_price,
                        "return_status": random.choice(["pending", "processed", "rejected"]),
                        "created_at": order_date + timedelta(days=random.randint(1, 14))
                    }
                    context.spawn(emit_event(ret, context))
                    return_id += 1
                    
                order_item_id += 1
                
            order = {
                "type": "order",
                "order_id": order_id,
                "customer_id": customer["customer_id"],
                "total_amount": round(total_amount, 2),
                "status": order_status,
                "created_at": order_date
            }
            context.spawn(emit_event(order, context))
            
            if order_status != "cancelled":
                payment = {
                    "type": "payment",
                    "transaction_id": f"txn-{order_id:010d}",
                    "order_id": order_id,
                    "customer_id": customer["customer_id"],
                    "amount": round(total_amount, 2),
                    "merchant": "MainRetailer",
                    "created_at": order_date,
                    "transaction_type": "purchase"
                }
                context.spawn(emit_event(payment, context))
            
            order_id += 1

    logger.info(f"Initializing fast-forward data engine (factor=0.0) for {args.days} days...")
    app.run(until=f"{args.days} days")
    logger.info(f"Data generation complete. Check '{args.dest_path}' for parquet files.")

def main():
    parser = argparse.ArgumentParser(description="E-Commerce Data Generator")
    parser.add_argument("--days", type=int, default=90, help="Number of days to simulate")
    parser.add_argument("--batch_size", type=int, default=50000, help="Batch size for Parquet files")
    parser.add_argument("--use_local", action="store_true", help="Write to local disk instead of S3")
    parser.add_argument("--dest_path", type=str, default="odctl-dev/landing", help="Destination path for parquet files")
    parser.add_argument("--random_seed", type=int, default=42, help="Random seed for determinism")
    
    args = parser.parse_args()
    # Deriving use_s3 boolean for internal logic
    args.use_s3 = not args.use_local
    run_simulation(args)

if __name__ == "__main__":
    main()
