import logging
import os
import random
import time
from datetime import timedelta

from dynamic_des import ParquetStorageEgress, SimulationContext

# Setup logging & determinism
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
random.seed(42)

def create_ecommerce_router(base_path: str):
    """
    Routes the events generated by the simulation into distinct Parquet files
    (e.g., customers.parquet, orders.parquet).
    """
    def router(data: dict) -> str | None:
        # Ignore internal system events and telemetry
        if data.get("path_id") == "system.simulation.lag_seconds":
            return None
        
        stream_type = data.get("stream_type")
        if stream_type == "telemetry":
            return None

        # Flatten event and route based on our custom "type" key
        if stream_type == "event" and "value" in data and isinstance(data["value"], dict):
            nested_value = data.pop("value")
            data.update(nested_value)
            
            event_type = data.get("type", "unknown")
            if event_type in ["customer", "product", "order", "order_item", "return", "payment"]:
                return f"{base_path}/{event_type}s/{event_type}s.parquet"
            
        return None
    return router

# ==========================================
# 1. GLOBAL CONFIGURATION
# ==========================================
days = int(os.getenv("DAYS", "30"))
batch_size = int(os.getenv("BATCH_SIZE", "10000"))
use_s3 = os.getenv("USE_S3", "false").lower() == "true"
base_path = os.getenv("DEST_PATH", "odctl-dev/landing" if use_s3 else "parquet_output")

logger.info("="*40)
logger.info("⚙️  DATA GENERATOR CONFIGURATION")
logger.info(f"Target Path:    {base_path}")
logger.info(f"Storage Type:   {'S3' if use_s3 else 'Local'}")
logger.info(f"Sim Days:       {days}")
logger.info(f"Batch Size:     {batch_size} (Dictates Parquet file size)")
logger.info("="*40)
filesystem = None

if use_s3:
    from pyarrow import fs
    # odctl defaults for SeaweedFS
    filesystem = fs.S3FileSystem(
        access_key=os.getenv("S3_ACCESS_KEY", "user"),
        secret_key=os.getenv("S3_SECRET_KEY", "password"),
        endpoint_override=os.getenv("S3_ENDPOINT", "localhost:8333"),
        scheme="http",
    )
    # Ensure bucket exists
    bucket = base_path.replace("s3://", "").split("/")[0]
    try:
        filesystem.create_dir(bucket)
    except Exception:
        pass
else:
    os.makedirs(base_path, exist_ok=True)

router = create_ecommerce_router(base_path)

# ==========================================
# 2. SIMULATION ENGINE
# ==========================================
# factor=0.0 means "fast-forward", meaning the simulation will instantly generate data
app = (
    SimulationContext(sim_id="ECommerce", factor=0.0, random_seed=42)
    .add_egress(ParquetStorageEgress(path_router=router, filesystem=filesystem))
    .with_batching(batch_size=batch_size, flush_interval=86400)
    .add_arrival("customer_signup", dist="exponential", rate=500.0 / 86400)
    .add_arrival("order_placement", dist="exponential", rate=10000.0 / 86400)
    .add_resource("data_generator", current_cap=1000, max_cap=1000)
    .add_service("event_emitter", dist="deterministic", mean=0.0)
)

# In-memory pools so orders can reference valid customers/products
customer_pool = []
product_pool = []

# ==========================================
# 3. GENERATORS
# ==========================================
@app.task(service_id="event_emitter", resource_id="data_generator")
def emit_event(event_dict, context):
    """A simple task whose only purpose is to return a dict so it gets dumped to Parquet."""
    return event_dict


@app.arrival_loop("customer_signup")
def generate_customers(context):
    # Initialize products exactly once
    if not product_pool:
        categories = ["Electronics", "Clothing", "Home", "Sports", "Toys"]
        for i in range(1, 21):
            product = {
                "type": "product",
                "product_id": i,
                "product_name": f"Product_{i}",
                "category": random.choice(categories),
                "price": round(random.uniform(10.0, 500.0), 2),
                "stock_quantity": random.randint(0, 1000),
                "created_date": (context.env.start_datetime + timedelta(seconds=context.env.now)).isoformat()
            }
            product_pool.append(product)
            context.spawn(emit_event(product, context))
            
    customer_id = 1
    # Generate customers continuously for the duration of the simulation
    while True:
        yield context.wait_for_arrival("customer_signup")
        customer = {
            "type": "customer",
            "customer_id": customer_id,
            "first_name": f"FirstName_{customer_id}",
            "last_name": f"LastName_{customer_id}",
            "loyalty_tier": random.choice(["Bronze", "Silver", "Gold", "Platinum"]),
            "registration_date": (context.env.start_datetime + timedelta(seconds=context.env.now)).isoformat()
        }
        customer_pool.append(customer)
        context.spawn(emit_event(customer, context))
        customer_id += 1

@app.arrival_loop("order_placement")
def generate_orders(context):
    order_id = 1
    order_item_id = 1
    return_id = 1
    
    # Generate orders continuously for the duration of the simulation
    while True:
        yield context.wait_for_arrival("order_placement")
        
        # Don't place an order if we don't have customers/products yet
        if not customer_pool or not product_pool:
            continue
            
        customer = random.choice(customer_pool)
        num_items = random.randint(1, 5)
        total_amount = 0
        order_date = (context.env.start_datetime + timedelta(seconds=context.env.now))
        
        # 1. Generate Order Items
        for _ in range(num_items):
            product = random.choice(product_pool)
            quantity = random.randint(1, 3)
            total_price = product["price"] * quantity
            total_amount += total_price
            
            is_returned = random.random() < 0.1
            
            order_item = {
                "type": "order_item",
                "order_item_id": order_item_id,
                "order_id": order_id,
                "product_id": product["product_id"],
                "quantity": quantity,
                "unit_price": product["price"],
                "total_price": total_price,
                "is_returned": is_returned,
                "timestamp": order_date.isoformat()
            }
            context.spawn(emit_event(order_item, context))
            
            # Generate a return if applicable
            if is_returned:
                ret = {
                    "type": "return",
                    "return_id": return_id,
                    "order_id": order_id,
                    "customer_id": customer["customer_id"],
                    "product_id": product["product_id"],
                    "refund_amount": total_price,
                    "return_status": random.choice(["pending", "processed", "rejected"]),
                    "timestamp": (order_date + timedelta(days=random.randint(1, 14))).isoformat()
                }
                context.spawn(emit_event(ret, context))
                return_id += 1
                
            order_item_id += 1
            
        # 2. Generate the Main Order
        order = {
            "type": "order",
            "order_id": order_id,
            "customer_id": customer["customer_id"],
            "total_amount": round(total_amount, 2),
            "status": random.choice(["pending", "shipped", "delivered", "cancelled"]),
            "timestamp": order_date.isoformat()
        }
        context.spawn(emit_event(order, context))
        
        # 3. Generate the Payment
        payment = {
            "type": "payment",
            "transaction_id": f"txn-{int(time.time() * 1000)}-{random.randint(1000,9999)}",
            "order_id": order_id,
            "customer_id": customer["customer_id"],
            "amount": round(total_amount, 2),
            "merchant": "MainRetailer",
            "timestamp": order_date.isoformat(),
            "transaction_type": "purchase"
        }
        context.spawn(emit_event(payment, context))
        
        order_id += 1

# ==========================================
# 4. EXECUTION
# ==========================================
def run():
    # Simulate the last N days of ecommerce activity
    logger.info(f"Initializing fast-forward data engine (factor=0.0) for {days} days...")
    
    # Detach clock and run operations instantly
    app.run(until=f"{days} days")
    
    logger.info(f"Data generation complete. Check '{base_path}' for parquet files.")

if __name__ == "__main__":
    run()
